const userData = [
  "Charles Xavier",
  "Scott Summers",
  "Robert Drake",
  "Henry McCoy",
  "Warren Worthington",
  "Jean Grey",
  "Kurt Wagner",
  "James Howlett",
  "Sean Cassidy",
  "Ororo Munroe",
  "Shiro Yoshida",
  "Piotr Nikolaievitch Rasputin",
  "Katherine Pryde",
  "Anna LeBeau",
  "Max Eisenhardt",
  "Erik Magnus",
  "Elizabeth Braddock",
  "Alison Blaire",
  "Remy Etienne",
  "Jubilation Lee",
  "Lucas Bishop",
  "Emma Frost",
  "Cain Marko",
];

const emailData = [
  "CharlesXavier@gmail.com",
  "ScottSummers@gmail.com",
  "RobertDrake@gmail.com",
  "HenryMcCoy@gmail.com",
  "WarrenWorthington@gmail.com",
  "JeanGrey@gmail.com",
  "KurtWagner@gmail.com",
  "JamesHowlett@gmail.com",
  "SeanCassidy@gmail.com",
  "OroroMunroe@gmail.com",
  "ShiroYoshida@gmail.com",
  "PiotrRasputin@gmail.com",
  "KatherinePryde@gmail.com",
  "AnnaLeBeau@gmail.com",
  "MaxEisenhardt@gmail.com",
  "ErikMagnus@gmail.com",
  "ElizabethBraddock@gmail.com",
  "AlisonBlaire@gmail.com",
  "RemyEtienne@gmail.com",
  "JubilationLee@gmail.com",
  "LucasBishop@gmail.com",
  "EmmaFrost@gmail.com",
  "CainMarko@gmail.com",
];

const thoughtData = [
  "Dont let yesterday take up too much of today",
  "If youre going through hell, keep going",
  "Every man dies. Not every man lives",
  "Life shrinks or expands in proportion to ones courage",
  "Nothing is impossible. The word itself says Im possible",
  "We need much less than we think we need",
  "If things go wrong, dont go with them",
  "Everything has beauty, but not everyone sees it",
  "Simplicity is the ultimate sophistication",
  "Whatever you are, be a good one",
  "Be yourself; everyone else is already taken",
  "Act as if what you do makes a difference. It does",
  "The only real mistake is the one from which we learn nothing",
  "Positive anything is better than negative nothing.",
  "Creativity is intelligence having fun",
  "If you tell the truth you dont have to remember anything",
  "There is no substitute for hard work",
  "Try to be a rainbow in someone elses cloud",
  "You do not find the happy life. You make it",
  "Sometimes you will never know the value of a moment, until it becomes a memory",
  "If you look at what you have in life, youll always have more",
  "Yesterdays the past, tomorrows the future, but today is a gift. Thats why its called the present",
  "Time moves in one direction, memory in another",
];

const reactionData = [
  "Woah! I love this!",
  "Nice!",
  "Hey, I like this!",
  "Yolo!",
  "Hmm, I dont know about this one",
  "Thats right!",
  "wow, this is great!",
  "Never thought of it that way",
  "Probably not",
  "Bad idea",
  "Boooooo!",
  "I second that!",
  "You are so right!",
  "I cant believe you said that!",
  "Omg, wow cant believe you said that!",
  "If you tel that is amazing and I love it!",
  "Tweedle dee, tweedle dum, I dont care for this one",
  "dam dum tic tac",
  "Please dont say that",
  "Come on, you can do better than that",
  "Totally agree",
  "My favorite!",
  "Not your best work",
];

// Export the data for use in seed.js
module.exports = { thoughtData, userData, emailData, reactionData };